name: First-action
on: workflow_dispatch

jobs:
  first-command:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: node -v

  second-command:
    runs-on: macos-latest
    steps:
      - name: check
        run: node -v
  third-command:
    runs-on: windows-latest
    steps:
      - name: check
        run: node -v