name: cashing-action
on: workflow_dispatch

jobs:
  cashing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkot@v4
      - name: cash
        id: cash-step
        uses: actions/cashe@v3
        with:
          path: ~/.npm
          key: 'cash-step'
      - name: Display cash
        run: echo ${{steps.cash-step.outputs}}
      - name: Node-modules install
        run: npm install
